"""Plain-text digest builder.

This module formats email-ready text only. It does not send email or connect to
an email provider.
"""

from hope_job_agent.models.match import JobMatch


def build_email_digest(student_name: str, matched_jobs: list[JobMatch]) -> str:
    """Build a plain-text digest for matched jobs."""

    lines = [
        f"Hello {student_name},",
        "",
        "Here are your current job matches:",
        "",
    ]

    if not matched_jobs:
        lines.append("No matches are available yet.")
    else:
        for index, match in enumerate(matched_jobs, start=1):
            job = match.job
            lines.extend(
                [
                    f"{index}. {job.title} at {job.company}",
                    f"   Location: {job.location}",
                    f"   Score: {match.score:.1f}",
                    f"   URL: {job.url}",
                    "",
                ]
            )

    lines.extend(
        [
            "",
            "This digest was generated by the HOPE MSIS Job Agent starter system.",
        ]
    )
    return "\n".join(lines).strip()
